# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

dist_euclidean <- function(x, y) {
    .Call(`_spima_dist_euclidean`, x, y)
}

dist_weighted_euclidean <- function(x, y, weights) {
    .Call(`_spima_dist_weighted_euclidean`, x, y, weights)
}

simulate_binary_studies <- function(n_ctrl, n_trt, p_ctrl, theta_i) {
    .Call(`_spima_simulate_binary_studies`, n_ctrl, n_trt, p_ctrl, theta_i)
}

simulate_cont_studies <- function(n_ctrl, n_trt, mean_ctrl, sd_ctrl, sd_trt, theta_i) {
    .Call(`_spima_simulate_cont_studies`, n_ctrl, n_trt, mean_ctrl, sd_ctrl, sd_trt, theta_i)
}

