// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// dist_euclidean
double dist_euclidean(NumericVector x, NumericVector y);
RcppExport SEXP _spima_dist_euclidean(SEXP xSEXP, SEXP ySEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type y(ySEXP);
    rcpp_result_gen = Rcpp::wrap(dist_euclidean(x, y));
    return rcpp_result_gen;
END_RCPP
}
// dist_weighted_euclidean
double dist_weighted_euclidean(NumericVector x, NumericVector y, NumericVector weights);
RcppExport SEXP _spima_dist_weighted_euclidean(SEXP xSEXP, SEXP ySEXP, SEXP weightsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type y(ySEXP);
    Rcpp::traits::input_parameter< NumericVector >::type weights(weightsSEXP);
    rcpp_result_gen = Rcpp::wrap(dist_weighted_euclidean(x, y, weights));
    return rcpp_result_gen;
END_RCPP
}
// simulate_binary_studies
NumericMatrix simulate_binary_studies(NumericVector n_ctrl, NumericVector n_trt, NumericVector p_ctrl, NumericVector theta_i);
RcppExport SEXP _spima_simulate_binary_studies(SEXP n_ctrlSEXP, SEXP n_trtSEXP, SEXP p_ctrlSEXP, SEXP theta_iSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type n_ctrl(n_ctrlSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type n_trt(n_trtSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type p_ctrl(p_ctrlSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type theta_i(theta_iSEXP);
    rcpp_result_gen = Rcpp::wrap(simulate_binary_studies(n_ctrl, n_trt, p_ctrl, theta_i));
    return rcpp_result_gen;
END_RCPP
}
// simulate_cont_studies
NumericMatrix simulate_cont_studies(NumericVector n_ctrl, NumericVector n_trt, NumericVector mean_ctrl, NumericVector sd_ctrl, NumericVector sd_trt, NumericVector theta_i);
RcppExport SEXP _spima_simulate_cont_studies(SEXP n_ctrlSEXP, SEXP n_trtSEXP, SEXP mean_ctrlSEXP, SEXP sd_ctrlSEXP, SEXP sd_trtSEXP, SEXP theta_iSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type n_ctrl(n_ctrlSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type n_trt(n_trtSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type mean_ctrl(mean_ctrlSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type sd_ctrl(sd_ctrlSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type sd_trt(sd_trtSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type theta_i(theta_iSEXP);
    rcpp_result_gen = Rcpp::wrap(simulate_cont_studies(n_ctrl, n_trt, mean_ctrl, sd_ctrl, sd_trt, theta_i));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_spima_dist_euclidean", (DL_FUNC) &_spima_dist_euclidean, 2},
    {"_spima_dist_weighted_euclidean", (DL_FUNC) &_spima_dist_weighted_euclidean, 3},
    {"_spima_simulate_binary_studies", (DL_FUNC) &_spima_simulate_binary_studies, 4},
    {"_spima_simulate_cont_studies", (DL_FUNC) &_spima_simulate_cont_studies, 6},
    {NULL, NULL, 0}
};

RcppExport void R_init_spima(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
